### ISSUE TITLE
Support new Mitre ATT&CK Sub-Technique numbering Scheme

### ISSUE THREAD

**Issue by clr2of8** [ION28/BLUESPAWN#350]
On July 8, 2020 Mitre change their numbering convention to support sub-techniques. Many of the base techniques numbers changed, some went away and new ones were added.

https://medium.com/mitre-attack/attack-subs-what-you-need-to-know-99bce414ae0b

**Comment by ION28** [comment]
Thanks for opening an issue for this @clr2of8! We had been delaying making this change until the beta went live, but now that it's out, we'll plan to get to it soon hopefully.

Additional Reference post for making these changes https://medium.com/mitre-attack/attack-with-sub-techniques-is-now-just-attack-8fc20997d8de

**Comment by Jack-McDowell** [comment]
My envisioned solution for this is to keep our codebase almost exactly how it was. The only change I think we really need to make is when we add context to detections created during a hunt. Say T1055 identifies a process that's using process doppelganging. Then we `CREATE_DETECTION_WITH_CONTEXT` instead of `CREATE_DETECTION`, and for our context, we do something like `DetectionContext{ GetName() + L" Subtechnique 013: Process Doppelganging" }`

Perhaps we can add a macro called something like `CREATE_DETECTION_SUBTECHNIQUE(subtechnique, ...)` that fills in everything but the subtechnique name and number. Oh, and we'll have to update the coverage map accordingly

**Comment by ION28** [comment]
That sounds good! I think we should slot this in after scan mode gets merged in probably

**Comment by ION28** [comment]
@clr2of8 We've made the necessary changes to support subtechniques and just opened a pull request to get these updates integrated into BLUESPAWN. These changes will make it up to the main branch and be included in our upcoming release (v0.5.0-alpha) next week. Going to go ahead and close this issue now, thanks for contributing!
